# Generated by Django 4.1.7 on 2023-03-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_id_alter_product_name'),
        ('inventory', '0002_remove_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
