# Generated by Django 4.1.7 on 2023-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('description', models.TextField(default=None)),
            ],
        ),
    ]
